name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['10.1.1', '10.1.2', '10.1.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: Build Extension
        run: gradle

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/
          retention-days: 7

  push_release:
    if: |
      github.event_name == 'push'
    needs: build_extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}
